### ISSUE TITLE
ebuildtester.docker.ExecuteFailure: failed command "eselect profile set default/linux/amd64/17.1"

### ISSUE THREAD

**Issue by oxr463** [nicolasbock/ebuildtester#123]
```sh
ebuildtester --portage-dir /mnt/src/gentoo --atom dev-libs/fyaml
2020-05-21 19:09:41,640 - creating container
2020-05-21 19:09:41,641 - creating docker container with: docker create --tty --cap-add SYS_ADMIN --device /dev/fuse --workdir /root --volume /mnt/src/gentoo:/var/db/repos/gentoo --volume /mnt/src/gentoo/distfiles:/var/cache/distfiles --volume /mnt/src/gentoo/packages:/var/cache/binpkgs gentoo/stage3-amd64
Unable to find image 'gentoo/stage3-amd64:latest' locally
latest: Pulling from gentoo/stage3-amd64
02a68cf0a387: Pulling fs layer
02a68cf0a387: Verifying Checksum
02a68cf0a387: Download complete
02a68cf0a387: Pull complete
Digest: sha256:6f11ceb375b6f5c33ad923ccc38dbae15c717a1dfc613cb3f479ea1f4e76109b
Status: Downloaded newer image for gentoo/stage3-amd64:latest
2020-05-21 19:13:37,542 - container id 3b82a4cc314af39cc37dc3d7d6dd0475ccfb57b4e60cfd4028f01030de485850
2020-05-21 19:13:39,766 - setting Gentoo profile to default/linux/amd64/17.1
2020-05-21 19:13:39,767 - 3b82a4 eselect profile set default/linux/amd64/17.1
2020-05-21 19:13:40,905 - 3b82a4 (stderr): sed: can't read /var/db/repos/gentoo/profiles/profiles.desc: No such file or directory
2020-05-21 19:13:40,907 - 3b82a4 (stderr): !!! Error: default/linux/amd64/17.1 is not a valid profile for amd64
2020-05-21 19:13:40,908 - 3b82a4 (stderr): exiting
2020-05-21 19:13:41,017 - running in container 3b82a4cc314af39cc37dc3d7d6dd0475ccfb57b4e60cfd4028f01030de485850
Traceback (most recent call last):
  File "/usr/bin/ebuildtester", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/ebuildtester/main.py", line 19, in main
    container = Docker(
  File "/usr/lib/python3.8/site-packages/ebuildtester/docker.py", line 28, in __init__
    self._set_profile()
  File "/usr/lib/python3.8/site-packages/ebuildtester/docker.py", line 188, in _set_profile
    self.execute("eselect profile set %s" % options.options.profile)
  File "/usr/lib/python3.8/site-packages/ebuildtester/docker.py", line 91, in execute
    raise ExecuteFailure("failed command \"%s\"" % (cmd))
ebuildtester.docker.ExecuteFailure: failed command "eselect profile set default/linux/amd64/17.1"
```

**Comment by stkw0** [comment]
Which version were you using? does it still happens? I think it was fixed some months ago

**Comment by oxr463** [comment]
> Which version were you using? does it still happens? I think it was fixed some months ago

Assuming https://github.com/nicolasbock/ebuildtester/releases/tag/v0.1.14 based on the date reported. I will try it again.

**Comment by nicolasbock** [comment]
Please let me know if this is still an issue @oxr463 .

**Comment by nicolasbock** [comment]
This works with the latest version @oxr463 . I will release an update soon.

**Comment by nicolasbock** [comment]
`v0.1.29` was released which should fix this issue. Please open another issue in case you run into this problem again.
