### ISSUE TITLE
Permission denied when running ebuildtester (snap)

### ISSUE THREAD

**Issue by RafaelPalomar** [nicolasbock/ebuildtester#196]
There seems to be a permissions issue when running `ebuildtester` installed through `snap`:

```console
2022-06-23 07:29:03,778 - creating container
Traceback (most recent call last):
  File "/snap/ebuildtester/160/bin/ebuildtester", line 8, in <module>
    sys.exit(main())
  File "/snap/ebuildtester/160/lib/python3.8/site-packages/ebuildtester/main.py", line 21, in main
    container = Docker(
  File "/snap/ebuildtester/160/lib/python3.8/site-packages/ebuildtester/docker.py", line 21, in __init__
    repo_names = self._get_repo_names(overlay_dirs)
  File "/snap/ebuildtester/160/lib/python3.8/site-packages/ebuildtester/docker.py", line 244, in _get_repo_names
    with open(os.path.join(o, "profiles/repo_name"), "r") as f:
PermissionError: [Errno 13] Permission denied: '/home/rafael/src/gentoo-science/profiles/repo_name'
```
`ls /home/rafael/src/gentoo-science/profiles/repo_name -lah` produces:

```console
-rw-rw-r-- 1 rafael rafael 8 Jun 22 12:15 /home/rafael/src/gentoo-science/profiles/repo_name
```

The `ebuildtester` installed following [https://ebuildtester.readthedocs.io/en/latest/contributing.html#](https://ebuildtester.readthedocs.io/en/latest/contributing.html#) works fine on the same invokation.

**Comment by nicolasbock** [comment]
Thanks for reporting @RafaelPalomar ! Could you share the exact command line you used to invoke `ebuildtester`?

**Comment by RafaelPalomar** [comment]
> Thanks for reporting @RafaelPalomar ! Could you share the exact command line you used to invoke `ebuildtester`?

```console
 ebuildtester --atom =sci-libs/itk-5.1.0 --portage-dir /home/rafael/src/gentoo --overlay-dir /home/rafael/src/gentoo-science --unmask =sci-libs/itk-5.1.0 --unmask =sci-libs/dcmtk-3.6.7 --features ccache --ccache /home/rafael/.var/cache/systole-cache
```
