### ISSUE TITLE
`docker: unknown server OS` error when launching ebuildtester (snap)

### ISSUE THREAD

**Issue by RafaelPalomar** [nicolasbock/ebuildtester#201]
Invoking:
 
```console
 ebuildtester --atom =sci-libs/itk-5.1.0 --portage-dir /home/rafael/src/gentoo\
 --overlay-dir /home/rafael/src/gentoo-science\
 --unmask =sci-libs/itk-5.1.0\
 --unmask =sci-libs/dcmtk-3.6.7 \
 --features ccache\
 --ccache /home/rafael/.var/cache/systole-cache
```
 produces:

```console
2022-06-23 12:36:22,488 - logging at /home/rafael/snap/ebuildtester/175/ebuildtester-sci-libs-itk.log
2022-06-23 12:36:22,488 - *** please note that all necessary licenses will be accepted ***
2022-06-23 12:36:22,488 - creating container
2022-06-23 12:36:22,488 - creating docker container with: docker-wrapper.sh create --tty --cap-add CAP_SYS_ADMIN --cap-add CAP_MKNOD --cap-add CAP_NET_ADMIN --security-opt apparmor:unconfined --device /dev/fuse --workdir /root --volume /home/rafael/src/gentoo:/var/db/repos/gentoo --volume /home/rafael/src/gentoo/distfiles:/var/cache/distfiles --volume /home/rafael/src/gentoo/packages:/var/cache/binpkgs --volume=/home/rafael/.var/cache/systole-cache:/var/tmp/ccache --volume=/home/rafael/src/gentoo-science:/var/lib/overlays/science gentoo/stage3
docker: unknown server OS: .
See 'docker create --help'.
Traceback (most recent call last):
  File "/snap/ebuildtester/175/bin/ebuildtester", line 8, in <module>
    sys.exit(main())
  File "/snap/ebuildtester/175/lib/python3.8/site-packages/ebuildtester/main.py", line 23, in main
    container = Docker(
  File "/snap/ebuildtester/175/lib/python3.8/site-packages/ebuildtester/docker.py", line 26, in __init__
    self._create_container(docker_image, local_portage,
  File "/snap/ebuildtester/175/lib/python3.8/site-packages/ebuildtester/docker.py", line 184, in _create_container
    raise Exception("failure creating docker container")
Exception: failure creating docker container
rafael@precision-5820-tower:/root$
```

**Comment by nicolasbock** [comment]
What user are you running ebuildtester as? Can you run

```
docker run hello-world
```

as that user?

**Comment by RafaelPalomar** [comment]
@nicolasbock, I think it is the configuration on my machine. I'll do some more testing and close the issue if it is related to my configuration.

**Comment by nicolasbock** [comment]
Ok, thanks. Let me know how it goes.

**Comment by RafaelPalomar** [comment]
Totally my setup. Sorry for the noise

**Comment by nicolasbock** [comment]
No worries 😄
