### ISSUE TITLE
Error while creating container

### ISSUE THREAD

**Issue by soltysek** [nicolasbock/ebuildtester#87]
I've tried to use this tool to test some ebuilds but it failed with nice python traceback:
``` 
ebuildtester --manual --portage-dir /usr/portage --overlay-dir /home/soltys/workspace/soltys-overlay
2018-07-09 15:38:47,133 - creating container
Using default tag: latest
latest: Pulling from gentoo/stage3-amd64
457fc2d084ea: Pull complete 
Digest: sha256:c731620786d8d0d222fe9656d99ea81ec2e3ec342c39ca3e37913c384b6a3470
Status: Downloaded newer image for gentoo/stage3-amd64:latest
2018-07-09 15:42:54,708 - creating docker container with: docker create --tty --cap-add SYS_ADMIN --device /dev/fuse --storage-opt size=50G --workdir /root --volume /usr/portage:/usr/portage --volume /usr/portage/distfiles:/usr/portage/distfiles --volume=/home/soltys/workspace/soltys-overlay:/var/lib/overlays/soltys-overlay gentoo/stage3-amd64
2018-07-09 15:42:57,869 - container id 21e1f0f8f7bad81fabcd55d30f9cd119a09977efa8f1a756f565e2b3f00e1e51
2018-07-09 15:42:59,598 - setting Gentoo profile to default/linux/amd64/17.0
2018-07-09 15:42:59,599 - 21e1f0 eselect profile set default/linux/amd64/17.0
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/ebuildtester", line 11, in <module>
    load_entry_point('ebuildtester==0.1.10', 'console_scripts', 'ebuildtester')()
  File "/usr/lib64/python2.7/site-packages/ebuildtester/main.py", line 21, in main
    [os.path.abspath(p) for p in options.options.overlay_dir])
  File "/usr/lib64/python2.7/site-packages/ebuildtester/docker.py", line 25, in __init__
    self._set_profile()
  File "/usr/lib64/python2.7/site-packages/ebuildtester/docker.py", line 159, in _set_profile
    self.execute("eselect profile set %s" % options.options.profile)
  File "/usr/lib64/python2.7/site-packages/ebuildtester/docker.py", line 64, in execute
    os.waitid(os.P_PID, stdout_reader, os.WEXITED)
AttributeError: 'module' object has no attribute 'waitid'```

It looks like this tool requires at least Python 3.3 as according to [Python 3 os module docs](https://docs.python.org/3/library/os.html#os.waitid)

Could you make it work also on Python 2.x or make it impossible to install this on Python 2.x?

**Comment by nicolasbock** [comment]
Hi @soltysek . Thanks for reporting this issue! Could you try it again with the current version and see whether it's reproducible? Thanks!
