### ISSUE TITLE
Error caused by --storage-opt

### ISSUE THREAD

**Issue by georgek** [nicolasbock/ebuildtester#88]
I've just installed Docker. Haven't done any configuration of it other than to add myself to docker group. Running as non-root:

```
ebuildtester --portage-dir /usr/portage/ --manual
2018-09-23 20:01:29,308 - creating container
Using default tag: latest
latest: Pulling from gentoo/stage3-amd64
8ba66ace1774: Pull complete 
Digest: sha256:80145371b9973ab35387caa7aa6c4350a1fbf5b60fe411254e3a78351e0e46ed
Status: Downloaded newer image for gentoo/stage3-amd64:latest
2018-09-23 20:05:27,135 - creating docker container with: docker create --tty --cap-add SYS_ADMIN --device /dev/fuse --storage-opt size=50G --workdir /root --volume /usr/portage:/usr/portage --volume /usr/portage/distfiles:/usr/portage/distfiles gentoo/stage3-amd64
Error response from daemon: --storage-opt is supported only for overlay over xfs with 'pquota' mount option
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/ebuildtester", line 11, in <module>
    load_entry_point('ebuildtester==0.1.10', 'console_scripts', 'ebuildtester')()
  File "/usr/lib64/python3.6/site-packages/ebuildtester/main.py", line 21, in main
    [os.path.abspath(p) for p in options.options.overlay_dir])
  File "/usr/lib64/python3.6/site-packages/ebuildtester/docker.py", line 23, in __init__
    zip(overlay_dirs, overlay_mountpoints))
  File "/usr/lib64/python3.6/site-packages/ebuildtester/docker.py", line 135, in _create_container
    raise Exception("failure creating docker container")
Exception: failure creating docker container
```

**Comment by nicolasbock** [comment]
Thanks for the report! I didn't configure mine this way and don't see this issue. I wonder why. What FS are you using?

**Comment by georgek** [comment]
I've also spoken to others on IRC who didn't have to do this. I'm use ext4 and didn't do any configuration of docker after I installed it. Reading the Docker docs, it seems using overlay2 as the storage driver by default is correct and normal behaviour even though the Gentoo docs say devicemapper should be the default.

**Comment by nicolasbock** [comment]
Thanks for the information, that's what I found as well. I think your PR is good to add though, regardless of what the default is supposed to be. You could add a sentence saying that setting the storage driver might be necessary if docker throws errors about `--storage-opt` but that the default might just work as advertised. Sorry for not being super clear here what to say :smile: But I think any kind of statement would help a user who faces this cryptic error message. Thanks!

**Comment by nicolasbock** [comment]
@georgek Do you think we can close this issue? Or should we add more information?

**Comment by georgek** [comment]
For me the issue is closed. I'm now happily using ebuildtester. I'm not sure if adding more info is necessary.

**Comment by powerman** [comment]
I'm using docker with overlay2 on ext4 and have this issue now.

I've removed line
```python
"--storage-opt", "size=50G",
```
in `/usr/lib64/python3.6/site-packages/ebuildtester/docker.py` and this fixed the issue.

```
$ docker info
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 17
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: zpsuptnxy3ft8y62wezq8vd2c
 Is Manager: true
 ClusterID: 4i0gm0730fwsd1340x3mbprcm
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8  
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.2.1
 Manager Addresses:
  192.168.2.1:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683b971d9c3ef73f284f176672c44b448662
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.19.23-gentoo
Operating System: Gentoo/Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 23.5GiB
Name: home
ID: KYEC:QF2P:LCGZ:G3PY:QWZE:VDLU:FWRS:G4RB:XHNQ:SDJS:5XS6:7V3R
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: powerman
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by nicolasbock** [comment]
Thanks for the info @powerman ! I'll try to reproduce this issue and understand why things are failing for some.
